services:
  api:
    image: deo-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deo-api
    restart: always
    ports:
      - "3003:3003"
    env_file:
      - path: .env
        required: false
      - path: .env.production
        required: false
    environment:
      - PORT=3003
    dns:
      - 8.8.8.8
      - 1.1.1.1